{% set name = "geonum" %}
{% set version = "1.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d787099f98affea4b67071bd9173ac25ddf968b77522cbb69d4696133d33be87

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - python >=3.8
    - scipy
    - matplotlib
    - latlon23
    - srtm.py
    - cartopy
    - setuptools

test:
  requires:
    - pytest
  imports:
    - setuptools
    - geonum
    - geonum.test
  commands:
    - py.test --pyargs geonum

about:
  home: https://github.com/jgliss/geonum
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Toolbox for 3D geonumerical calculations
  doc_url: https://geonum.readthedocs.io/
  dev_url: https://github.com/jgliss/geonum

extra:
  recipe-maintainers:
    - jgliss
