{% set name = "geonum" %}
{% set version = "1.5.1" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3fb4dcff566d0087433aa681372cbb8cb8c5bf4ff6db448cbf9a665c6f0d77cd

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base
    - latlon23
    - srtm.py
    - cartopy
    - setuptools

test:
  requires:
    - pytest
    - netcdf4
    - python {{ python_min }}
  source_files:
    - test
  imports:
    - geonum
  commands:
    - pytest -Wi test

about:
  home: https://github.com/jgliss/geonum
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Toolbox for 3D geonumerical calculations
  doc_url: https://geonum.readthedocs.io/
  dev_url: https://github.com/jgliss/geonum

extra:
  recipe-maintainers:
    - jgliss
