travis:
  secure:
    BINSTAR_TOKEN: pY3sUlS1sK+iBJycvF8W+qCHGzQtPkDiRb68AIay8alNE4LqvXGGtLNg4fgNPXlJe7A2QFSdt2tbny4D1wdd4i1/gQ0ll/b9cEsR/eOsf2PyyWeVBUaOxYwJtKsbOtwuJLxwRjKJ7awsmwtaAWbsW6QqaT184qHig3n3pNV1OZ6k5ndwEGDrr705W7GaslTdXR6UxrKncsmug7Pf/nU+gd3YtKTAwKUiA1qtWxLXxYXPUMPjGDbTMNiitPMvHcN+izmWyTvkMLQEy08ETakL21jtxbBjCabrEYZnBNio6tG4Z9Oc5VqhPSjQJm5w7CpmFPpkVI74rDotNRDJPpKpqSeI8zHf9Unbxjq1BUEH1VWiEhRg9u9dxzGct58vrNyZzHxYUDbDU7l4f6o8jQvtaEKoFYBO3ea76SPAhrdmTCV9M+IST1xdOitgWLpORst+WLy49kNwBXqU3PbYwZUh6rX+FjLuDArlrmwA7fwbYP1ZCmRzt0nFBBIuoSkIHxOC0AwPWK3AEuQe+0q0us911Qj83XfSaxVemleY3q8ROZV/XCm5Pxh54SZGxjCO66hcb6Y2DFcOUUMsAvVc3KXzebhMyPbk4S6fkepWtSo6sciNhQHoTg51CMm5WqeW1Ojjht5qoZKYLYZvKieD+KYoA374GwTXLGEJf8hkmDofL4k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
